version: '3.8'

services:
  translate-text-edu:
    image: sebast19/translate-azure:latest  
    ports:
      - "8080:8080"  
    environment:
      DATABASE_URL: ${DATABASE_URL}          
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
